<?php

define('GETID3_RECOMMEND_VERSION', '1.8.2');

/**
 * Implements hook_help().
 */
function getid3_help($section, $arg) {
  switch ($section) {
    case 'admin/config/media/getid3':
      $help = '<p>' . t("To use this module you'll need to <a href='!download-link'>download the library</a> from the <a href='!info-link'>getID3 website</a> and extract the contents into the site's libraries directory. Currently, the recommended version of the getID3 library is %recommended-version.",
        array('!download-link' => url('http://prdownloads.sourceforge.net/getid3'), '!info-link' => url('http://getid3.org/'), '%recommended-version' => GETID3_RECOMMEND_VERSION)) . '</p>';
      return $help;
  }
}

/**
 * Implements hook_menu().
 */
function getid3_menu() {
  $items['admin/config/media/getid3'] = array(
    'title' => 'getID3()',
    'description' => 'Configure settings associated with getID3().',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('getid3_admin_settings_form', NULL),
    'access arguments' => array('administer site configuration'),
    'file' => 'getid3.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function getid3_theme($existing, $type, $theme, $path) {
  return array(
    'getid3_duration' => array(
      'variables' => array('duration' => NULL),
    ),
    'getid3_sample_rate' => array(
      'variables' => array('sample_rate' => NULL),
    ),
    'getid3_bitrate' => array(
      'variables' => array('bitrate' => NULL),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function getid3_libraries_info() {
  $libraries['getID3'] = array(
    'name' => 'getID3',
    'vendor url' => 'http://www.getid3.org',
    'download url' => 'https://sourceforge.net/projects/getid3/files/getID3%28%29%201.x',
    'path' => 'getid3',
    'version' => '1.9.8', // @TODO: Move this into version_callback and version_arguments.
    'files' => array(
      'php' => array(
        'getid3.php',
      ),
    ),
  );
  return $libraries;
}


/**
 * Load the getID3 library.
 *
 * @return
 *   Boolean indicating if the library was successfully loaded.
 */
function getid3_load($display_warning = TRUE) {
  // Ensure the getID3() library is loaded.
  $library = libraries_detect('getID3');
  if ($library['installed']) {
    libraries_load('getID3');
    return TRUE;
  }
  return FALSE;
}

/**
 * Create and initialize an instance of getID3 class.
 */
function getid3_instance() {
  $id3 = NULL;
  if (getid3_load()) {
    $id3 = new getID3();
    // MD5 is a big performance hit. Disable it by default.
    $id3->option_md5_data = FALSE;
    $id3->option_md5_data_source = FALSE;
    $id3->encoding = 'UTF-8';
  }
  return $id3;
}

/**
 * Takes a file entity object and returns ID3 data.
 * @param $file
 * @return null|array
 */
function getid3_analyze_file($file) {
  // Initialize
  $getID3 = getid3_instance();
  $file_realpath = drupal_realpath($file->uri);

  // Verify file exists, as external files are saved as managed files
  // Ex: this prevents errors on media_youtube or media_vimeo entries.
  if (file_exists($file_realpath)) {
    // Analyze.
    return $getID3->analyze($file_realpath);
  }

  return NULL;
}

/**
 * Implements hook_file_presave().
 */
function getid3_file_presave($file) {
  // Make sure we do not try to extract ID3 data from non valid types.
  if (!in_array($file->type, array('video', 'audio'))) {
    return null;
  }

  // Load the ID3 data.
  $id3_data = getid3_analyze_file($file);

  // If we have data, attach it to metadata.
  if ($id3_data) {

    // Set the duration
    if (isset($id3_data['playtime_string'])) {
      $file->metadata['duration'] = $id3_data['playtime_string'];
    }

    // Update video specific information.
    if (isset($id3_data['video'])) {
      $file->metadata['width'] = $id3_data['video']['resolution_x'];
      $file->metadata['height'] = $id3_data['video']['resolution_y'];
    }

    // Update audio specific information.
    if (isset($info['audio'])) {
      $file->metadata['audio_format'] = $info['audio']['dataformat'];
      $file->metadata['audio_sample_rate'] = $info['audio']['sample_rate'];
      $file->metadata['audio_channel_mode'] = $info['audio']['channelmode'];
      $file->metadata['audio_bitrate'] = isset($info['audio']['bitrate']) ? $info['audio']['bitrate'] : NULL;
      $file->metadata['audio_bitrate_mode'] = isset($info['audio']['bitrate_mode']) ? $info['audio']['bitrate_mode'] : NULL;
    }
  }

  // @TODO: Kill off the audio module by allowing users to edit id3 tags on
  // files. Explore a sub-module that allows tags to be mapped to CCK fields and
  // allows reading and writing of the tags.

  // Add in arbitrary ID3 tags.
  if (isset($id3_data['tags_html'])) {
    // We use tags_html instead of tags because it is the most reliable data
    // source for pulling in non-UTF-8 characters according to getID3 docs.
    foreach ($id3_data['tags_html'] as $type => $values) {
      // Typically $type may be IDv2 (for MP3s) or quicktime (for AAC).
      foreach ($values as $key => $value) {
        $value = isset($value[0]) ? (string) $value[0] : (string) $value;
        if (!empty($value) && $key != 'coverart') {
          $file->metadata['tags'][$key] = html_entity_decode($value, ENT_QUOTES, 'UTF-8');
        }
      }
    }
  }
}

/**
 * Implements hook_views_api().
 */
function getid3_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'getid3') . '/includes',
  );
}

/**
 * Format a float duration into minutes:seconds.
 *
 * @param $variables
 *   Array with 'duration' key.
 */
function theme_getid3_duration($variables) {
  $duration = $variables['duration'];
  $seconds = round((($duration / 60) - floor($duration / 60)) * 60);
  $minutes = floor($duration / 60);
  if ($seconds >= 60) {
    $seconds -= 60;
    $minutes++;
  }
  return ((int) $minutes) . ':' . str_pad($seconds, 2, 0, STR_PAD_LEFT);
}

/**
 * Format an audio sample rate.
 *
 * @param $variables
 *   Array with 'sample_rate' key.
 */
function theme_getid3_sample_rate($variables) {
  return t('@sampleratekHz', array('@samplerate' => (int) ($variables['sample_rate'] / 1000)));
}

/**
 * Format an audio bitrate.
 *
 * @param $variables
 *   Array with 'bitrate' key.
 */
function theme_getid3_bitrate($variables) {
  return t('@bitrateKbps', array('@bitrate' => (int) ($variables['bitrate'] / 1000)));
}
